name: Vercel Deployment Status

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Wait for Vercel Deployment
        run: |
          echo "🚀 Deployment triggered on Vercel"
          echo "View status at: https://vercel.com/dashboard"
          echo "Latest commit: ${{ github.sha }}"
          
      - name: Deployment Info
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.event.head_commit.message }}"

